name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Arduino sketch
        uses: arduino/compile-sketches@v1.1.2
        with:
          sketch-paths: |
            ./FanControl
            ./TachInput
          libraries: |
            - source-path: './libraries/TDComm'
            - source 
